[tool.poetry]
name = "allocator-bot"
version = "0.1.0"
description = "An asset allocation bot for OpenBB that uses PyPortfolioOpt to generate efficient frontier allocations."
authors = ["Theodore Aptekarev <aptekarev@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
openbb-core = "^1.3.7"
magentic = "^0.34.1"
pandas = "^2.2.3"
pyportfolioopt = "^1.5.6"
theobb = "^1.0.0"
openbb-equity = "^1.3.5"
openbb-etf = "^1.3.5"
sse-starlette = "^2.1.3"
openbb-fmp = "^1.3.5"
tabulate = "^0.9.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
